version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'

  # Keep devcontainer features up-to-date
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      devcontainer-features:
        patterns:
          - "*"
