baseURL: "https://bugbountycoi.org/"

module:
  imports:
    - disable: false
      path: "github.com/theNewDynamic/gohugo-theme-ananke/v2"

resourceDir: "./resources"
defaultContentLanguage: "en"
sectionPagesMenu: "main"
googleAnalytics: ""
enableRobotsTXT: true

languages:
  en:
    title: "Bug Bounty Community of Interest"
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

# ananake-specific configuration parameters
# can also be set per-page in front matter
params:
  text_color: ""
  author: ""
  favicon: ""
  site_logo: ""
  description: ""
  show_reading_time: true
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: bg-black
  recent_posts_number: 3
  since: 2019
  ananke:
    # TODO: don't think I did this right
    social:
      follow:
        networks:
          - github
          - linkedin
        new_window_icon: true  # Optional: adds external link icon
      github:
        profilelink: "https://github.com/bugbountycoi"
        icon: "github"
      linkedin:
        profilelink: "https://www.linkedin.com/company/bb-coi"
        icon: "linkedin"



# Can also define in page front matter instead of globally
# https://gohugo.io/content-management/menus/
menus:
  main:
    # Note: we don't have a content/posts/ right now
    - name: "Posts"
      weight: 1
      identifier: "posts"
      url: "/posts"

    - name: "Join Us"
      weight: 2
      identifier: "join"
      url: "/join"

    - name: "CFP"
      weight: 2
      identifier: "cfp"
      url: "/cfp"

    - name: "Framework"
      weight: 3
      identifier: "framework"
      url: "/framework"

    #- name: "Terms of Service"
    #  weight: 4
    #  identifier: "terms-of-service"
    #  url: "/terms-of-service"

    #- name: "Code of Conduct"
    #  weight: 5
    #  identifier: "code-of-conduct"
    #  url: "/code-of-conduct"
