baseURL: "https://bugbountycoi.org/"
languageCode: "en-us"
title: "Bug Bounty COI"

module:
  imports:
    - disable: false
      path: "github.com/theNewDynamic/gohugo-theme-ananke/v2"

resourceDir: "./resources"
defaultContentLanguage: "en"
sectionPagesMenu: "main"
googleAnalytics: ""
enableRobotsTXT: true

languages:
  en:
    title: "Bug Bounty COI"
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

# ananake-specific configuration parameters
# can also be set per-page in front matter
params:
  text_color: ""
  author: ""
  favicon: ""
  site_logo: ""
  description: ""
  show_reading_time: true
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: bg-black
  recent_posts_number: 3
  ananke:
    # TODO: don't think I did this right
    social:
      follow:
        github:
          url: "https://github.com/bugbountycoi"

# Can also define in page front matter instead of globally
# https://gohugo.io/content-management/menus/
menu:
  main:
    # Note: we don't have a content/posts/ right now
    - name: "Posts"
      weight: 1
      identifier: "posts"
      url: "/posts"

    - name: "Call For Presentations"
      weight: 2
      identifier: "cfp"
      url: "/cfp"

    - name: "Industry Framework"
      weight: 3
      identifier: "framework"
      url: "/framework"

    - name: "Join Us"
      weight: 99
      identifier: "join"
      url: "/join"
