name: Spellcheck
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
    - uses: rojopolis/spellcheck-github-actions@1cae94c93fd55bef22af91927fe3412fd4a0d726
      name: Spellcheck
      with:
        config_path: config/spellcheck.yml 
