name: Spellcheck
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
    - uses: rojopolis/spellcheck-github-actions@19bf2a1ed294bac1ed941f64e38d25b353003b05
      name: Spellcheck
      with:
        config_path: config/spellcheck.yml 
